### ISSUE TITLE
MiniTest style stub is clobbering RSpec's

### ISSUE THREAD

**Issue by zephyr-dev** [moonmaster9000/quacky#4]
It appears my project has MiniTest and RSpec.

```
 Failure/Error: before { information_request.stub(:startup).and_return(startup) }
     ArgumentError:
       wrong number of arguments (1 for 2)
     # /Users/pivotal/.rvm/gems/ruby-1.9.3-p194@gust/gems/quacky-0.2.5/lib/quacky/minitest_setup.rb:25:in `stub'
     # ./spec/models/ability_spec.rb:596:in `block (3 levels) in <top (required)>'
```

**Comment by zephyr-dev** [comment]
It appears a brand-new Rails 3.2.8 project created with "--skip-test-unit" has the MiniTest constant defined

**Comment by benmoss** [comment]
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/test_case.rb#L2 gets loaded by Rails when RSpec loads. It seems to be a result of RSpec's controller tests, which rely on ActionController::TestCase under the hood.
